### ISSUE TITLE
Working with monopati on Trisquel 9

### ISSUE THREAD

**Issue by dancesWithCycles** [comzeradd/monopati#2]
Hi folks,
I thank you very much for offering and maintaining this repository!

I started to use it for my personal [website](https://begerad.de). I can work on Debian 10 but sometimes I would like to work on Trisquel 9. That is a free as in free speech operating system approved by the Free Software Foundation based on Ubuntu 18.04. 'pip' is not allowed on Trisquel because it makes accidental installation of non-free software easy.

Do you know a work around so that I can use `monopati` on `Trisquel`?

When I call the binary file from the repository to render the website (```~/git/dancesWithCycles/monopati/bin/monopati render```) I receive the following message.

```
Traceback (most recent call last):
  File "/home/stefan/git/dancesWithCycles/monopati/bin/monopati", line 30, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
```

I appreciate any advice that points me in the right direction!

Cheers!

**Comment by comzeradd** [comment]
Hi @dancesWithCycles 

Glad that `monopati` turned out to be useful for you 🙂 

The first step would be to install the [monopati's python dependencies](https://github.com/comzeradd/monopati/blob/master/setup.py#L15-L20) using `apt` instead of `pip`. As far as I can see, all of them are packaged for Trisquel. So this should work:

```
apt install python3-yaml python3-docopt python3-jinja2 python3-markdown
```

The second step is to add the monopati path to `$PYTHONPATH`, so the executable can work properly. In your case that should work:

```
export PYTHONPATH="${HOME}/git/dancesWithCycles/monopati/"
```

If you want to make this change permanent you can add the above line in your `~/.bashrc`.

Now `monopati` should run fine:

```
~/git/dancesWithCycles/monopati/bin/monopati -h
```

**Comment by dancesWithCycles** [comment]
Dear Nikos,
I am pleased I came across your repository for the following reasons:

- I appreciate your prompt and helpful reply. With your help I have got `monopati` running on `Trisquel 9` and can go on with website development.
- It is always an awesome feeling to meet people with similar values and see that the world is small. Before I moved to Columbia, Maryland I volunteered for Greenpeace Germany for about four years and still have contact.

Cheers!
